config/routes.rb
ListenLoop::Application.routes.draw do

  resources :presentations do
    resources :slides
  end

  root 'presentations#index'

end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  has_many :slides
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  belongs_to :presentation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: [:show, :edit, :update, :destroy]

  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.all
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new
  end

  # GET /presentations/1/edit
  def edit
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @presentation = Presentation.new(presentation_params)

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to @presentation, notice: 'Presentation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @presentation }
      else
        format.html { render action: 'new' }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1
  # PATCH/PUT /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to @presentation, notice: 'Presentation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(:link, :title)
    end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  def index
    @presentation = Presentation.find(params[:presentation_id])
  end

  def new
    @presentation = Presentation.find(params[:presentation_id])
    @slide = @presentation.slides.new
  end

  def create
    @presentation = Presentation.find(params[:presentation_id])
    @slide = @presentation.slides.new(slide_params)
    if @slide.save
      flash[:success] = "Successfully created..."
      redirect_to presentation_slides_path
    else
      flash[:error] = "Not created..."
      render action: :new
    end
  end

  private

  def slide_params
    params[:slide].permit(:feedback)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ListenLoop</title>
  <%= csrf_meta_tags %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>
<body>

<div class='container'>
  <%= yield %>
</div>

<script type="text/javascript">
$( document ).ready(function() {
  $( "#generate" ).on( "click", function() {
    alert('Generating Presentation...');
  });

    $( "#email" ).on( "click", function() {
    alert('Emailing to Client...');
  });
});
</script>
</body>
</html>

app/views/presentations/_form.html.erb
<%= form_for(@presentation) do |f| %>
  <% if @presentation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@presentation.errors.count, "error") %> prohibited this presentation from being saved:</h2>

      <ul>
      <% @presentation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presentations/edit.html.erb
<h1>Editing presentation</h1>

<%= render 'form' %>

<%= link_to 'Show', @presentation %> |
<%= link_to 'Back', presentations_path %>

app/views/presentations/index.html.erb
<h1>Listing presentations</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Title</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @presentations.each do |presentation| %>
      <tr>
        <td><%= presentation.link %></td>
        <td><%= presentation.title %></td>
        <td>
          <%= link_to 'Manage Slides', presentation_slides_path(presentation) %>
          <%= link_to 'Generate Presentation', presentation, :target => "_blank" %>
          <%= link_to 'Edit', edit_presentation_path(presentation) %>
          <%= link_to 'Destroy', presentation, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presentation', new_presentation_path %>

app/views/presentations/new.html.erb
<h1>New presentation</h1>

<%= render 'form' %>

<%= link_to 'Back', presentations_path %>

app/views/presentations/show.html.erb
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Reveal.js 3 Slide Demo</title>
    <link rel="stylesheet" href="css/reveal.min.css">
    <link rel="stylesheet" href="css/theme/default.css" id="theme">
    <!--Add support for earlier versions of Internet Explorer -->
    <!--[if lt IE 9]>
    <script src="lib/js/html5shiv.js"></script>
    <![endif]-->
</head>

<body>
  <!-- Wrap the entire slide show in a div using the "reveal" class. -->
  <div class="reveal">
      <!-- Wrap all slides in a single "slides" class -->
      <div class="slides">

          <!-- ALL SLIDES GO HERE -->
          <section>
              <h1><%= @presentation.title %></h1>
              <p>Greetings Customer! Here is what the last five clients said about you...</p>
          </section>

          <% @last_five = @presentation.slides.find(:all, :limit => 5) %>
          <% @last_five.each do |slide| %>
            <section>
              <h1>Feedback #<%= slide.id %></h1>
              <%= slide.feedback %>
            </section>
          <% end %>

          </div>
  </div>
  <script src="lib/js/head.min.js"></script>
  <script src="js/reveal.min.js"></script>

  <script>
  $( document ).ready(function() {
    // Required, even if empty.
    Reveal.initialize({
    });
  });
  </script>
</body>
</html>

app/views/slides/index.html.erb
<h1><%= @presentation.title %></h1>

<ul class='slides'>
  <% @presentation.slides.each do |slide| %>
    <li><%= slide.feedback %></li>
  <% end %>
</ul>

<p>
  <%= link_to "Add Next Feedback", new_presentation_slide_path %>
  <br>
  <%= link_to "Back to Presentations", presentations_path %>
</p>

app/views/slides/new.html.erb
<%= form_for [@presentation, @slide] do |f| %>
  <%= f.label :feedback%>
  <%= f.text_field :feedback %>
  <%= f.submit "Save" %>
<% end %>